# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '13.5'
  # Pods for iosApp
  pod 'kotlin_library', :path => '../kotlin-library'
end

target 'MacosCLI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :osx, '10.15'
  
  # Pods for MacosCLI
  pod 'kotlin_library', :path => '../kotlin-library'
  
end

target 'TVosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :tvos, '13.4'
  
  # Pods for TVosApp
  pod 'kotlin_library', :path => '../kotlin-library'
end

target 'WatchosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :watchos, '6.2'
  
  # Pods for WatchosApp
  pod 'kotlin_library', :path => '../kotlin-library'
end

target 'WatchosApp WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :watchos, '6.2'
  
  # Pods for WatchosApp WatchKit App
  pod 'kotlin_library', :path => '../kotlin-library'
end

target 'WatchosApp WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :watchos, '6.2'

  # Pods for WatchosApp WatchKit Extension
  pod 'kotlin_library', :path => '../kotlin-library'
end
